import {initializeApp} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";import {getAuth,onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";import {getFirestore,doc,getDoc,setDoc} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
const firebaseConfig = {
  apiKey: "AIzaSyBv2m_ciaohvHg7xCqkSWeTM_TfiphzMqw",
  authDomain: "pisotrack-e61d6.firebaseapp.com",
  projectId: "pisotrack-e61d6",
  storageBucket: "pisotrack-e61d6.firebasestorage.app",
  messagingSenderId: "492013865042",
  appId: "1:492013865042:web:e0ccf6e2bee76aab32f78b"
};

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
function safeEmailKey(email){return String(email||"guest").replaceAll("@","_at_").replaceAll(".","_dot_").replaceAll("+","_plus_")}
function transactionKey(email){return "transactions_"+safeEmailKey(email)}
function normalizeTransactions(raw){if(Array.isArray(raw))return raw;if(typeof raw==="string"){try{const p=JSON.parse(raw);return Array.isArray(p)?p:[]}catch(e){return []}}return []}
function money(v,currency="PHP",rate=56.5){if(currency==="USD")return "$"+(Number(v||0)/rate).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});return "₱"+Number(v||0).toLocaleString("en-PH",{minimumFractionDigits:0,maximumFractionDigits:2})}
async function getAppData(user){const ref=doc(db,"users",user.uid,"appData","default"),snap=await getDoc(ref);return {ref,data:snap.exists()?snap.data():{}}}
async function getTransactions(user){const {data}=await getAppData(user);return normalizeTransactions(data[transactionKey(user.email)]??data[transactionKey(data.currentEmail)]??data.transactions)}
async function saveTransactions(user,list){const ref=doc(db,"users",user.uid,"appData","default");await setDoc(ref,{currentEmail:user.email,email:user.email,[transactionKey(user.email)]:JSON.stringify(list),updatedAt:Date.now()},{merge:true})}
async function getSettings(user){const {data}=await getAppData(user);return {currency:data.currency||"PHP",notifications:data.notifications!==false,dark:data.dark===true,phpPerUsd:typeof data.phpPerUsdNumber==="number"?data.phpPerUsdNumber:56.5}}
async function saveSettings(user,values){const ref=doc(db,"users",user.uid,"appData","default");await setDoc(ref,{...values,currentEmail:user.email,email:user.email,updatedAt:Date.now()},{merge:true})}
function applyDark(v){document.documentElement.classList.toggle("dark",!!v);if(document.body)document.body.classList.toggle("dark",!!v)}
function fmtDate(ms){return new Date(Number(ms)).toLocaleDateString("en-US",{timeZone:"Asia/Manila",month:"short",day:"2-digit",year:"numeric"})}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function phtDateValue(date=new Date()){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Manila",year:"numeric",month:"2-digit",day:"2-digit"}).format(date)}function phtTimestamp(value){return new Date(value+"T12:00:00+08:00").getTime()}

let currentUser,allTx=[],settings,editingIndex=-1,currentType="expense";
range.innerHTML='<option>All</option><option>Today</option><option>Last Week</option><option>This Week</option><option>This Month</option><option>Last Month</option><option>Last 3 Months</option><option>This Year</option>';range.value="All";
function rangeBounds(){const[y,m,d]=phtDateValue().split("-").map(Number),dayMs=86400000,phtOffset=8*60*60*1000,today=Date.UTC(y,m-1,d),weekDay=(new Date(today).getUTCDay()+6)%7,thisWeek=today-weekDay*dayMs,toPht=calendarUtc=>calendarUtc-phtOffset;switch(range.value){case"Today":return[toPht(today),toPht(today+dayMs)];case"This Week":return[toPht(thisWeek),toPht(thisWeek+7*dayMs)];case"Last Week":return[toPht(thisWeek-7*dayMs),toPht(thisWeek)];case"This Month":return[toPht(Date.UTC(y,m-1,1)),toPht(Date.UTC(y,m,1))];case"Last Month":return[toPht(Date.UTC(y,m-2,1)),toPht(Date.UTC(y,m-1,1))];case"Last 3 Months":return[toPht(Date.UTC(y,m-3,1)),toPht(Date.UTC(y,m,1))];case"This Year":return[toPht(Date.UTC(y,0,1)),toPht(Date.UTC(y+1,0,1))];default:return[-Infinity,Infinity]}}
function filtered(useSearch=true){const[start,end]=rangeBounds(),query=useSearch?searchTx.value.trim().toLowerCase():"";return allTx.map((t,i)=>({...t,_i:i})).filter(t=>Number(t.time)>=start&&Number(t.time)<end&&(category.value==="All"||String(t.category).toLowerCase()===category.value.toLowerCase())&&(!query||String(t.title||"").toLowerCase().includes(query)||String(t.category||"").toLowerCase().includes(query)))}
function render(){const f=filtered();let inc=0,exp=0;allTx.forEach(t=>t.type==="income"?inc+=Number(t.amount):exp+=Number(t.amount));const balance=inc-exp;net.textContent=money(Math.abs(balance),settings.currency,settings.phpPerUsd);list.innerHTML=f.length?f.slice().reverse().map(t=>`<div class="tx-row"><div><div class="tx-title">${esc(t.title)} • ${esc(t.category)}</div><div class="tx-date">${fmtDate(t.time)}</div></div><div class="tx-amount">${t.type==="income"?"+":"-"}${money(t.amount,settings.currency,settings.phpPerUsd)}</div><button class="btn secondary edit" data-i="${t._i}">Edit</button></div>`).join(""):'<div class="empty">No transactions for this filter.</div>';document.querySelectorAll(".edit").forEach(b=>b.onclick=()=>openEdit(Number(b.dataset.i)))}
function fillCategories(){const cats=[...new Set(allTx.map(t=>t.category).filter(Boolean))].sort();category.innerHTML='<option>All</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join("")}
const incomeCategories=["Salary","Allowance","Business","Freelance","Bonus","Gift","Scholarship","Investment","Refund","Other Income"],expenseCategories=["Food","Transportation","School","Bills","Shopping","Entertainment","Health","Rent","Utilities","Internet / Load","Personal Care","Family","Pet Expenses","Debt / Loan","Other Expense"];
const oldCategoryInput=document.getElementById("txCategory"),txCategorySelect=document.createElement("select");txCategorySelect.id="txCategory";txCategorySelect.className="select";oldCategoryInput.replaceWith(txCategorySelect);const otherCategoryField=document.createElement("div");otherCategoryField.className="field-hidden";otherCategoryField.innerHTML='<label>Specify category</label><input id="txOtherCategory" class="input" maxlength="50">';txCategorySelect.insertAdjacentElement("afterend",otherCategoryField);const txOtherCategory=document.getElementById("txOtherCategory");
function setTxCategories(type,value){const choices=type==="income"?incomeCategories:expenseCategories;txCategorySelect.innerHTML=choices.map(item=>`<option>${esc(item)}</option>`).join("");if(value&&!choices.includes(value)){txCategorySelect.insertAdjacentHTML("beforeend",`<option>${esc(value)}</option>`)}txCategorySelect.value=value||choices[0];toggleOtherCategory()}
function toggleOtherCategory(){const other=txCategorySelect.value==="Other Income"||txCategorySelect.value==="Other Expense";otherCategoryField.classList.toggle("field-hidden",!other);txOtherCategory.required=other;if(!other)txOtherCategory.value=""}
txCategorySelect.onchange=toggleOtherCategory;
function maximumTransactionDate(){return phtDateValue(new Date(Date.now()+86400000))}
function openAdd(type){editingIndex=-1;currentType=type;modal.classList.remove("editing");deleteTx.hidden=true;modalTitle.textContent=type==="income"?"Add Income":"Add Expense";txTitle.value="";setTxCategories(type);txAmount.value="";txDate.value=phtDateValue();txMessage.classList.remove("show");modal.classList.add("open")}
function openEdit(i){editingIndex=i;const t=allTx[i];currentType=t.type;modal.classList.add("editing");deleteTx.hidden=false;modalTitle.textContent="Edit Transaction";txTitle.value=t.title;setTxCategories(t.type,t.category);if(t.category==="Other Income"||t.category==="Other Expense")txOtherCategory.value=t.category;txAmount.value=settings.currency==="USD"?(Number(t.amount)/settings.phpPerUsd).toFixed(2):Number(t.amount).toFixed(2);txDate.value=phtDateValue(new Date(Number(t.time)));txMessage.classList.remove("show");modal.classList.add("open")}
addExpense.onclick=()=>openAdd("expense");addIncome.onclick=()=>openAdd("income");cancel.onclick=()=>modal.classList.remove("open");category.onchange=render;range.onchange=render;searchTx.oninput=render;
save.onclick=async()=>{const amount=Number(txAmount.value),isOther=txCategorySelect.value.startsWith("Other "),selectedCategory=isOther?txOtherCategory.value.trim():txCategorySelect.value;if(!txTitle.value.trim()||!selectedCategory||!amount||!txDate.value)return;if(txDate.value>maximumTransactionDate()){txMessage.textContent="This date is not valid because that day has not arrived yet. You may only select up to one day ahead.";txMessage.classList.add("show");return}const php=settings.currency==="USD"?amount*settings.phpPerUsd:amount;const item={title:txTitle.value.trim(),category:selectedCategory,amount:php,type:currentType,time:phtTimestamp(txDate.value)};if(editingIndex>=0)allTx[editingIndex]=item;else allTx.push(item);await saveTransactions(currentUser,allTx);modal.classList.remove("open");fillCategories();render()};
deleteTx.onclick=async()=>{if(editingIndex<0)return;const deleteIndex=editingIndex,transaction=allTx[deleteIndex],confirmed=await window.pisoTrackConfirm({title:"Delete Transaction?",message:`Are you sure you want to delete ${transaction.title||"this transaction"}? This action cannot be undone.`,confirmText:"Delete",danger:true});if(!confirmed)return;deleteTx.disabled=true;try{allTx.splice(deleteIndex,1);await saveTransactions(currentUser,allTx);modal.classList.remove("open");editingIndex=-1;fillCategories();render()}catch(error){allTx.splice(deleteIndex,0,transaction);console.error(error);txMessage.textContent="Could not delete the transaction. Please try again.";txMessage.classList.add("show")}finally{deleteTx.disabled=false}};
onAuthStateChanged(auth,async user=>{if(!user)return location.href="login.html";if(!user.emailVerified){await signOut(auth);return location.href="login.html"}currentUser=user;userName.textContent=user.displayName||user.email;try{settings=await getSettings(user);localStorage.setItem("pisotrackDark",String(settings.dark));applyDark(settings.dark)}catch(error){console.error(error);settings={currency:"PHP",notifications:true,dark:document.documentElement.classList.contains("dark"),phpPerUsd:56.5}}allTx=await getTransactions(user);fillCategories();render()});
