
import {initializeApp} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import {getAuth,onAuthStateChanged,signOut,updateProfile,updatePassword,verifyBeforeUpdateEmail,EmailAuthProvider,reauthenticateWithCredential,sendPasswordResetEmail} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import {getFirestore,doc,getDoc,setDoc} from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";

const firebaseConfig = {
  apiKey: "AIzaSyBv2m_ciaohvHg7xCqkSWeTM_TfiphzMqw",
  authDomain: "pisotrack-e61d6.firebaseapp.com",
  projectId: "pisotrack-e61d6",
  storageBucket: "pisotrack-e61d6.firebasestorage.app",
  messagingSenderId: "492013865042",
  appId: "1:492013865042:web:e0ccf6e2bee76aab32f78b"
};

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
function safeEmailKey(email){return String(email||"guest").replaceAll("@","_at_").replaceAll(".","_dot_").replaceAll("+","_plus_")}
function transactionKey(email){return "transactions_"+safeEmailKey(email)}
function normalizeTransactions(raw){if(Array.isArray(raw))return raw;if(typeof raw==="string"){try{const p=JSON.parse(raw);return Array.isArray(p)?p:[]}catch(e){return []}}return []}
function money(v,currency="PHP",rate=56.5){if(currency==="USD")return "$"+(Number(v||0)/rate).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});return "₱"+Number(v||0).toLocaleString("en-PH",{minimumFractionDigits:0,maximumFractionDigits:2})}
async function getAppData(user){const ref=doc(db,"users",user.uid,"appData","default"),snap=await getDoc(ref);return {ref,data:snap.exists()?snap.data():{}}}
async function getTransactions(user){const {data}=await getAppData(user);return normalizeTransactions(data[transactionKey(user.email)]??data[transactionKey(data.currentEmail)]??data.transactions)}
async function saveTransactions(user,list){const ref=doc(db,"users",user.uid,"appData","default");await setDoc(ref,{currentEmail:user.email,email:user.email,[transactionKey(user.email)]:JSON.stringify(list),updatedAt:Date.now()},{merge:true})}
async function getSettings(user){const {data}=await getAppData(user);return {currency:data.currency||"PHP",notifications:data.notifications!==false,dark:data.dark===true,phpPerUsd:typeof data.phpPerUsdNumber==="number"?data.phpPerUsdNumber:56.5}}
async function saveSettings(user,values){const ref=doc(db,"users",user.uid,"appData","default");await setDoc(ref,{...values,currentEmail:user.email,email:user.email,updatedAt:Date.now()},{merge:true})}
function applyDark(v){document.documentElement.classList.toggle("dark",!!v);if(document.body)document.body.classList.toggle("dark",!!v)}
function fmtDate(ms){return new Date(Number(ms)).toLocaleDateString("en-US",{month:"short",day:"2-digit",year:"numeric"})}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}

let user,shown=false,settings;function maskEmail(e){const at=e.indexOf("@");if(at<=1)return"••••"+e.substring(Math.max(0,at));return e[0]+"••••••"+e.substring(at)}
const profileActions=document.querySelector(".profile-actions");
let forgotPasswordButton=document.getElementById("forgotPassword");
if(!forgotPasswordButton){forgotPasswordButton=document.createElement("button");forgotPasswordButton.id="forgotPassword";forgotPasswordButton.type="button";forgotPasswordButton.className="wide-pattern";forgotPasswordButton.textContent="Forgot Password";profileActions.insertBefore(forgotPasswordButton,document.getElementById("logout"))}
forgotPasswordButton.style.setProperty("display","block","important");
document.body.insertAdjacentHTML("beforeend",'<div class="modal" id="forgotPasswordModal"><form class="modal-box" id="forgotPasswordForm"><h3>Forgot Password</h3><p class="confirm-help">Enter your email address and PisoTrack will send you a secure password-reset link.</p><div id="forgotPasswordMessage" class="message" role="status"></div><label for="forgotPasswordEmail">Email Address</label><input id="forgotPasswordEmail" class="input" type="email" required autocomplete="email"><div class="modal-actions"><button id="cancelForgotPassword" class="btn secondary" type="button">Cancel</button><button id="sendResetEmail" class="btn" type="submit">Send Email</button></div></form></div>');
const forgotPasswordModal=document.getElementById("forgotPasswordModal"),forgotPasswordForm=document.getElementById("forgotPasswordForm"),forgotPasswordEmail=document.getElementById("forgotPasswordEmail"),forgotPasswordMessage=document.getElementById("forgotPasswordMessage"),sendResetEmail=document.getElementById("sendResetEmail"),cancelForgotPassword=document.getElementById("cancelForgotPassword");
forgotPasswordButton.onclick=()=>{forgotPasswordForm.reset();forgotPasswordEmail.disabled=false;sendResetEmail.hidden=false;forgotPasswordEmail.value=user?.email||"";forgotPasswordMessage.className="message";forgotPasswordMessage.textContent="";forgotPasswordModal.classList.add("open");forgotPasswordEmail.focus()};
cancelForgotPassword.onclick=()=>forgotPasswordModal.classList.remove("open");
forgotPasswordModal.onclick=event=>{if(event.target===forgotPasswordModal)forgotPasswordModal.classList.remove("open")};
forgotPasswordForm.onsubmit=async event=>{event.preventDefault();const email=forgotPasswordEmail.value.trim();if(!email)return;sendResetEmail.disabled=true;try{await sendPasswordResetEmail(auth,email,{url:new URL("login.html",location.href).href});forgotPasswordMessage.textContent="Email received. Check your inbox and click the secure PisoTrack reset link.";forgotPasswordMessage.className="message show success";forgotPasswordEmail.disabled=true;sendResetEmail.hidden=true}catch(error){forgotPasswordMessage.textContent="Unable to send the reset email. Check the address and try again.";forgotPasswordMessage.className="message show error"}finally{sendResetEmail.disabled=false}};
const passwordLabel=[...document.querySelectorAll(".info-label")].find(label=>label.textContent.trim()==="Password:");
const passwordRow=passwordLabel?.nextElementSibling;
if(passwordRow)passwordRow.innerHTML='<span id="passwordValue" class="password-value">••••••••</span><button id="passwordEye" class="icon-button" type="button" aria-label="Show password"><img src="eyeofficon.png" alt=""></button>';
document.body.insertAdjacentHTML("beforeend",'<div class="modal" id="passwordModal"><form class="modal-box" id="passwordConfirmForm"><h3>Confirm Password</h3><p class="confirm-help">Enter your current password to reveal it.</p><div id="passwordConfirmMessage" class="message error" role="alert"></div><label for="passwordConfirmInput">Current Password</label><input id="passwordConfirmInput" class="input" type="password" required autocomplete="current-password"><div class="modal-actions"><button id="cancelPasswordConfirm" class="btn secondary" type="button">Cancel</button><button id="confirmPassword" class="btn" type="submit">Confirm</button></div></form></div>');
const passwordValue=document.getElementById("passwordValue"),passwordEye=document.getElementById("passwordEye"),passwordEyeImage=passwordEye?.querySelector("img");
const passwordModal=document.getElementById("passwordModal"),passwordConfirmForm=document.getElementById("passwordConfirmForm"),passwordConfirmInput=document.getElementById("passwordConfirmInput"),passwordConfirmMessage=document.getElementById("passwordConfirmMessage"),confirmPassword=document.getElementById("confirmPassword"),cancelPasswordConfirm=document.getElementById("cancelPasswordConfirm");
let passwordShown=false;
function hidePassword(){passwordShown=false;passwordValue.textContent="••••••••";passwordEyeImage.src="eyeofficon.png";passwordEye.setAttribute("aria-label","Show password")}
passwordEye.onclick=()=>{if(passwordShown){hidePassword();return}passwordConfirmForm.reset();passwordConfirmMessage.classList.remove("show");passwordModal.classList.add("open");passwordConfirmInput.focus()};
cancelPasswordConfirm.onclick=()=>passwordModal.classList.remove("open");
passwordModal.onclick=event=>{if(event.target===passwordModal)passwordModal.classList.remove("open")};
passwordConfirmForm.onsubmit=async event=>{event.preventDefault();const entered=passwordConfirmInput.value;if(!user||!entered)return;confirmPassword.disabled=true;try{const credential=EmailAuthProvider.credential(user.email,entered);await reauthenticateWithCredential(user,credential);passwordValue.textContent=entered;passwordShown=true;passwordEyeImage.src="eyeshowicon.png";passwordEye.setAttribute("aria-label","Hide password");passwordConfirmInput.value="";passwordConfirmMessage.className="message error";passwordModal.classList.remove("open")}catch(error){passwordConfirmMessage.textContent="The password is incorrect. Please try again.";passwordConfirmMessage.className="message show error"}finally{confirmPassword.disabled=false}};
emailEye.onclick=()=>{shown=!shown;emailValue.textContent=shown?user.email:maskEmail(user.email);emailEye.src=shown?"eyeshowicon.png":"eyeofficon.png"};
editInfo.onclick=()=>{editName.value=user.displayName||"";editEmail.value=user.email||"";currentPassword.value="";newPassword.value="";editModal.classList.add("open")};cancelEdit.onclick=()=>editModal.classList.remove("open");
saveEdit.onclick=async()=>{try{const newName=editName.value.trim(),newEmail=editEmail.value.trim(),cp=currentPassword.value,np=newPassword.value;if(!newName||!newEmail)return;const emailChanged=newEmail!==user.email,passChanged=!!np,nameChanged=newName!==(user.displayName||"");if(passChanged&&np.length<8)throw new Error("New password must be at least 8 characters.");if(emailChanged||passChanged){if(!cp)throw new Error("Enter your current password first.");const cred=EmailAuthProvider.credential(user.email,cp);await reauthenticateWithCredential(user,cred)}if(nameChanged)await updateProfile(user,{displayName:newName});if(passChanged)await updatePassword(user,np);if(emailChanged)await verifyBeforeUpdateEmail(user,newEmail,{url:new URL("login.html",location.href).href});await setDoc(doc(db,"users",user.uid),{uid:user.uid,name:newName,email:user.email},{merge:true});nameValue.textContent=newName;emailValue.textContent=shown?user.email:maskEmail(user.email);if(emailChanged){msg.textContent="Verification sent to your new email address. Your account email will change after you verify it.";msg.className="message show success";editEmail.value=user.email;currentPassword.value="";newPassword.value=""}else{editModal.classList.remove("open")}}catch(e){msg.textContent=e.message||"Unable to update profile.";msg.className="message show error"}};
clearTx.onclick=async()=>{if(await window.pisoTrackConfirm({title:"Clear Transactions?",message:"Are you sure you want to clear all of your transactions? This action cannot be undone.",confirmText:"Clear",danger:true})){await saveTransactions(user,[]);alert("Transactions cleared.")}};logout.onclick=async()=>{if(!await window.pisoTrackConfirm({title:"Log Out?",message:"Are you sure you want to log out?",confirmText:"Log Out"}))return;await signOut(auth);location.href="login.html"};
onAuthStateChanged(auth,async u=>{if(!u)return location.href="login.html";if(!u.emailVerified){await signOut(auth);return location.href="login.html"}user=u;await setDoc(doc(db,"users",u.uid),{uid:u.uid,name:u.displayName||"User",email:u.email},{merge:true});try{settings=await getSettings(u);localStorage.setItem("pisotrackDark",String(settings.dark));applyDark(settings.dark)}catch(error){console.error(error);settings={currency:"PHP",notifications:true,dark:document.documentElement.classList.contains("dark"),phpPerUsd:56.5}}nameValue.textContent=u.displayName||"User";emailValue.textContent=maskEmail(u.email||"")});
